cnki/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import views

cnki/app/main/views.py
# coding=utf8
from flask import render_template, request
from . import bp
from app.models import *
from app import q, db
import requests
import time
from rq import Queue
from app.helper import crawler
from math import ceil
from sqlalchemy.sql import text
import more_itertools

def get_or_create(session, model, **kwargs):
    instance = session.query(model).filter_by(**kwargs).first()
    if instance:
        return instance
    else:
        instance = model(**kwargs)
        session.add(instance)
        session.commit()
        return instance

@bp.route('/', methods=['GET', 'POST'])
def index():
    papers_count = db.session.query(Paper).count()
    keywords_count = db.session.query(Keyword).count()
    return render_template('main/index.html',
                           papers_count=papers_count,
                           keywords_count=keywords_count)

@bp.route('/search_query', methods=['GET'])
def search_query():
    query = request.args.get('query')
    query_results = db.session.query(Paper).filter(Paper.title.like("%{0}%".format(query))).all()
    result_sql = text("select keyword_id, count(*) FROM keywords where paper_id in :paper_ids GROUP BY keyword_id ORDER BY count(*) DESC limit 10;")
    result = db.engine.execute(result_sql, paper_ids=tuple([k.id for k in query_results])).fetchall()
    top10_keywords = [{'keyword': db.session.query(Keyword).get(r[0]).keyword, 'count': r[1]} for r in result]
    keywords_label = [k['keyword'] for k in top10_keywords]
    counts = [k['count'] for k in top10_keywords]
    year_result_sql = text(
            "select year, count(*) from paper where title like :query group by year order by count(*);"
    )
    years_result = [tuple([k, v]) for k,v in db.engine.execute(year_result_sql, query='%{0}%'.format(query)).fetchall() if k]
    years_label = [r[0] for r in years_result]
    years_counts = [r[1] for r in years_result]

    orgs_result = [(db.session.query(Organization).get(a).organization, b) for a,b in [(k, v) for k, v in db.engine.execute("select orgainzation_id, count(*) from organizations where paper_id in {0} group by orgainzation_id order by count(*) desc limit 10;".format(tuple([p.id for p in query_results])))]]
    orgs_label = [r[0] for r in orgs_result]
    orgs_counts = [r[1] for r in orgs_result]

    return render_template('main/more.html', top10_keywords=top10_keywords,
                           keywords_label=keywords_label, counts=counts,
                           years_label=years_label, years_counts=years_counts,
                           years_result=years_result, orgs_label=orgs_label,
                           orgs_counts=orgs_counts)



@bp.route('/search', methods=['GET'])
def search():
    query = request.args.get('query')
    page = request.args.get('page', type=int, default=1)
    per_page = 10
    papers = db.session.query(Paper).filter(Paper.title.like("%{0}%"\
            .format(query))).offset((page-1)*per_page).limit(per_page)
    total_pages = int(ceil(db.session.query(Paper).count() / per_page))
    count = db.session.query(Paper).filter(Paper.title.like("%{0}%".format(query))).count()
    return render_template('main/papers.html', papers=papers, page=page, total_pages=total_pages, query=query)

@bp.route('/paper/<int:id>')
def paper(id):
    paper = db.session.query(Paper).get(id)
    return render_template('main/paper.html', paper=paper)

@bp.route('/author/<int:id>')
def author(id):
    author = db.session.query(Author).get(id)
    author_papers = author.papers
    related_authors = []
    related_authors_meta = []
    for p in author_papers:
        for a in p.authors:
            #if not a == author and a not in related_authors_meta:
            if not a == author:
                is_in = False
                for i in related_authors:
                    if a.id == i['id']:
                        is_in = True

                if not is_in:
                    related_authors.append({'id': a.id, 'author': a.author, 'times': 1})
                if a in related_authors_meta:
                    for i, dic in enumerate(related_authors):
                        if dic['id'] == a.id:
                            dic['times'] += 1
                related_authors_meta.append(a)
    print(related_authors)

    papers_join_sql = text("select paper_id from author inner join authors on author.id = authors.author_id where author.id=:author_id;")
    papers_join = [r[0] for r in db.engine.execute(papers_join_sql, author_id=id).fetchall()]
    papers = db.session.query(Paper).filter(Paper.id.in_(tuple(papers_join))).all()
    keywords = []
    keywords_meta = []
    for paper in author.papers:
        for keyword in paper.keywords:
            is_in = False
            for i in keywords:
                if keyword.id == i['id']:
                    is_in = True
            if not is_in:
                keywords.append({'id': keyword.id, 'keyword': keyword.keyword, 'times': 1})
            if keyword in keywords_meta:
                for i, dic in enumerate(keywords):
                    if dic['id'] == keyword.id:
                        dic['times'] += 1
            keywords_meta.append(keyword)

    return render_template('main/author.html', author=author, papers=papers,
                           related_authors=related_authors, keywords=keywords)

@bp.route('/more', methods=['GET'])
def more():
    result = db.engine.execute("select keyword_id, count(*) FROM keywords GROUP BY keyword_id ORDER BY count(*) DESC;").fetchall()
    # top 10 keywords
    top10_keywords = [{'keyword': db.session.query(Keyword).get(r[0]).keyword, 'count': r[1]} for r in result[0:10]]
    keywords_label = [k['keyword'] for k in top10_keywords]
    counts = [k['count'] for k in top10_keywords]
    years_result = [tuple([k, v]) for k,v in db.engine.execute("select year, count(*) from paper group by year order by count(*);").fetchall() if k]
    orgs_result = [(db.session.query(Organization).get(a).organization, b) for a,b in [(k, v) for k, v in db.engine.execute("select orgainzation_id, count(*) from organizations group by orgainzation_id order by count(*) desc limit 10;")]]
    orgs_label = [r[0] for r in orgs_result]
    orgs_counts = [r[1] for r in orgs_result]
    #years_result = db.engine.execute("select year, count(*) from paper group by year order by count(*) desc;").fetchall()
    years_label = [r[0] for r in years_result]
    years_counts = [r[1] for r in years_result]
    return render_template('main/more.html', top10_keywords=top10_keywords,
                           keywords_label=keywords_label,
                           counts=counts, years_result=years_result,
                           years_label=years_label, years_counts=years_counts,
                           orgs_label=orgs_label, orgs_counts=orgs_counts)

@bp.route('/consume', methods=['GET'])
def consume():
    while True:
        papers = db.session.query(Paper).filter((Paper.in_queue == None)\
                | (Paper.in_queue == 0)).all()

        # push paper to queue
        #for paper in papers[1:10]:
        for paper in papers:
            job = q.enqueue(crawler, paper.id, paper.url)
            time.sleep(3)
            result = job.result
            if result:
                print(result)
                keywords = result['keywords']
                organizations = result['organizations']
                authors = result['authors']
                record_keywords = []
                record_organizations = []
                record_authors = []
                if keywords:
                    for keyword in keywords:
                        keyword = get_or_create(db.session, Keyword, keyword=keyword)
                        record_keywords.append(keyword)
                        db.session.add(keyword)
                else:
                    record_keywords = []

                for organization in organizations:
                    organization = get_or_create(db.session, Organization, organization=organization)
                    record_organizations.append(organization)
                    db.session.add(organization)

                for author in authors:
                    author = get_or_create(db.session, Author, author=author)
                    record_authors.append(author)
                    db.session.add(author)

                paper.description = result['abstract']
                paper.year = result['year']
                paper.in_queue = 1
                paper.keywords = record_keywords
                paper.organizations = record_organizations
                paper.authors = record_authors
                db.session.add(paper)
                db.session.commit()

cnki/app/templates/main/index.html
{% extends "layout.html" %}
{% block subtitle %}首页{% endblock %}
{% block active %}active{% endblock %}

{% block body %}
<div class="inner cover">
  <h1 class="cover-heading">知网</h1>
  <p class="lead">基于关键词的论文爬取和分析系统的设计与实现</p>
  <p>{{ papers_count }} 篇论文 | {{ keywords_count }} 个关键词 </p>
  <p class="lead">
  <a href="{{ url_for('main.more')  }}" class="btn btn-lg btn-secondary">更多</a>
  </p>
</div>
{% endblock %}
{% block background %}
{% endblock %}

cnki/app/templates/main/more.html
{% extends 'layout.html' %}
{% set active_page = 'more' %}
{% block active_charts %}active{%endblock%}
{% block position %}clear{% endblock %}
{% block searchbox %}
<form name='search' action='/search_query' method='GET'>
  <input type="text" class="form-control searchbox" name='query' placeholder="搜索关键词">
  <input type="submit" style="position: absolute; left: -9999px"/>
</form>
{% endblock %}

{% block body %}

{% if not fuzzy %}
<div class="main">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#keywords-tab" role="tab">关键词</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#years-tab" role="tab">年份</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#orgs-tab" role="tab">大学机构</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="keywords-tab" role="tabpanel">
      <label>
        十大关键词饼图
        <canvas id="keywords-chart" width="500" height="500"></canvas>
      </label>
    </div>
    <div class="tab-pane" id="years-tab" role="tabpanel">
      <label>
        年份图表
      </label>
      <canvas id="years-chart" width="500" height="500"></canvas>
    </div>
    <div class="tab-pane" id="orgs-tab" role="tabpanel">
      <label>
        大学机构图表
      </label>
      <canvas id="orgs-chart" width="500" height="500"></canvas>
    </div>
  </div>
  <script>
Chart.defaults.global.legend.display = false;
var orgs_ctx = $('#orgs-chart');
var myChart = new Chart(orgs_ctx, {
  type: 'bar',
  data: {
    labels: {{ orgs_label|safe }},
    datasets: [{
      label: '总计',
      data: {{ orgs_counts|safe }},
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(25, 23, 23, 0.2)',
        'rgba(219, 61, 61, 0.2)',
        'rgba(0, 242, 255, 0.2)',
        'rgba(0, 8, 247, 0.2)',
      ]
    }]
  }
});
var keyword_ctx = $("#keywords-chart");
var myChart = new Chart(keyword_ctx, {
  type: 'bar',
  data: {
    labels: {{ keywords_label|safe }},
    datasets: [{
      label: '总计',
      data: {{ counts|safe }},
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(25, 23, 23, 0.2)',
        'rgba(219, 61, 61, 0.2)',
        'rgba(0, 242, 255, 0.2)',
        'rgba(0, 8, 247, 0.2)',
      ],
      borderWidth: 1,

    }]
  }});
var years_ctx = $("#years-chart");
var myChart = new Chart(years_ctx, {
  type: 'line',
  data: {
    labels: {{ years_label|safe }},
    datasets: [{
      label: '总计',
      data: {{ years_counts|safe }},
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(25, 23, 23, 0.2)',
        'rgba(219, 61, 61, 0.2)',
        'rgba(0, 242, 255, 0.2)',
        'rgba(0, 8, 247, 0.2)',
      ],
      borderColor: [
        'rgba(255,99,132,1)',
        'rgba(54, 162, 235, 1)',
        'rgba(255, 206, 86, 1)',
        'rgba(75, 192, 192, 1)',
        'rgba(153, 102, 255, 1)',
        'rgba(255, 159, 64, 1)',
        'rgba(25, 23, 23, 1)',
        'rgba(219, 61, 61, 1)',
        'rgba(0, 242, 255, 1)',
        'rgba(0, 8, 247, 1)',
      ],
      borderWidth: 1,
      options: {
        legend: {
          display: false
        },
      }
    }]
  },
  options: {
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero:true
        }
      }]
    }
  }
});
  </script>
</div>
{% else %}
{{ fuzzy|safe }}
{% endif %}
{% endblock %}

{% block background %}
{% endblock %}

cnki/app/templates/main/papers.html
{% extends "layout.html" %}

{% block body %}

<div class="body">
  {% for paper in papers %}
  <p><a href='/paper/{{ paper.id }}'>{{ paper.title }}</a></p>
  {% endfor %}
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <a class="page-link" href="{{ url_for('main.search', query=query, page=page-1) }}"> <li class="page-item {% if page==1 %}disabled{% endif %}">上一页</li></a>
      <a class="page-link" href="{{ url_for('main.search', query=query, page=page+1) }}"> <li class="page-item {% if page==total_pages%} disabled {% endif %}">下一页</li></a>
    </ul>
  </nav>
</div>

{% endblock %}